name: Deploy Boss Night to GitHub Pages

on:
  push:
    branches: [master]
    paths:
      - 'standalone-bossnight/**'
      - '.github/workflows/deploy-bossnight-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare site
        run: |
          mkdir -p _site
          cp standalone-bossnight/index.html standalone-bossnight/app.js standalone-bossnight/styles.css _site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
